// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deletalanguage.sql

package database

import (
	"context"
)

const deleteLanguage = `-- name: DeleteLanguage :exec
DELETE FROM languages WHERE code = $1
`

func (q *Queries) DeleteLanguage(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, deleteLanguage, code)
	return err
}
