// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getlanguagebycode.sql

package database

import (
	"context"
)

const getLanguageByCode = `-- name: GetLanguageByCode :one
SELECT id, code, name FROM languages WHERE code = $1
`

func (q *Queries) GetLanguageByCode(ctx context.Context, code string) (Language, error) {
	row := q.db.QueryRowContext(ctx, getLanguageByCode, code)
	var i Language
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}
