// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getlanguagebynmb.sql

package database

import (
	"context"
)

const getLanguageById = `-- name: GetLanguageById :one
SELECT id, code, name FROM languages WHERE id = $1
`

func (q *Queries) GetLanguageById(ctx context.Context, id int32) (Language, error) {
	row := q.db.QueryRowContext(ctx, getLanguageById, id)
	var i Language
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}
