// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getlistbyfrequency.sql

package database

import (
	"context"
)

const getListByFrequency = `-- name: GetListByFrequency :many
SELECT token_name, last_seen_at, known, frequency, promted_user_to_mark FROM words WHERE frequency > 1 ORDER BY known ASC, frequency DESC
`

func (q *Queries) GetListByFrequency(ctx context.Context) ([]Word, error) {
	rows, err := q.db.QueryContext(ctx, getListByFrequency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.TokenName,
			&i.LastSeenAt,
			&i.Known,
			&i.Frequency,
			&i.PromtedUserToMark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
