// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getlanguagelist.sql

package database

import (
	"context"
)

const getLanguageList = `-- name: GetLanguageList :many
SELECT id, code, name FROM languages
`

func (q *Queries) GetLanguageList(ctx context.Context) ([]Language, error) {
	rows, err := q.db.QueryContext(ctx, getLanguageList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
