// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getword.sql

package database

import (
	"context"
)

const getWord = `-- name: GetWord :one
SELECT token_name, last_seen_at, known, frequency FROM words WHERE token_name = $1
`

func (q *Queries) GetWord(ctx context.Context, tokenName string) (Word, error) {
	row := q.db.QueryRowContext(ctx, getWord, tokenName)
	var i Word
	err := row.Scan(
		&i.TokenName,
		&i.LastSeenAt,
		&i.Known,
		&i.Frequency,
	)
	return i, err
}
