// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getwords.sql

package database

import (
	"context"
)

const getWords = `-- name: GetWords :many
SELECT token_name, last_seen_at, known, frequency, promted_user_to_mark, language_id FROM words
WHERE language_id = $1
`

func (q *Queries) GetWords(ctx context.Context, languageID int32) ([]Word, error) {
	rows, err := q.db.QueryContext(ctx, getWords, languageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.TokenName,
			&i.LastSeenAt,
			&i.Known,
			&i.Frequency,
			&i.PromtedUserToMark,
			&i.LanguageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
