// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: insertword.sql

package database

import (
	"context"
)

const createWord = `-- name: CreateWord :one
INSERT INTO words (token_name, last_seen_at, known, frequency)
VALUES (
    $1,
    now(),
    $2,
    1
)
RETURNING token_name, last_seen_at, known, frequency, promted_user_to_mark
`

type CreateWordParams struct {
	TokenName string
	Known     bool
}

func (q *Queries) CreateWord(ctx context.Context, arg CreateWordParams) (Word, error) {
	row := q.db.QueryRowContext(ctx, createWord, arg.TokenName, arg.Known)
	var i Word
	err := row.Scan(
		&i.TokenName,
		&i.LastSeenAt,
		&i.Known,
		&i.Frequency,
		&i.PromtedUserToMark,
	)
	return i, err
}
