// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: insertlanguage.sql

package database

import (
	"context"
)

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages (code, name)
VALUES (
    $1,
    $2
)
RETURNING id, code, name
`

type CreateLanguageParams struct {
	Code string
	Name string
}

func (q *Queries) CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error) {
	row := q.db.QueryRowContext(ctx, createLanguage, arg.Code, arg.Name)
	var i Language
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}
