// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Word struct {
	TokenName  string
	LastSeenAt time.Time
	Known      bool
	Frequency  int32
}
