// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resetdb.sql

package database

import (
	"context"
)

const resetLanguages = `-- name: ResetLanguages :exec
TRUNCATE languages RESTART IDENTITY CASCADE
`

func (q *Queries) ResetLanguages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetLanguages)
	return err
}

const resetWords = `-- name: ResetWords :exec
TRUNCATE words RESTART IDENTITY CASCADE
`

func (q *Queries) ResetWords(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetWords)
	return err
}
