// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resetlanguage.sql

package database

import (
	"context"
)

const resetLangWords = `-- name: ResetLangWords :exec
DELETE FROM words
WHERE language_id = $1
`

func (q *Queries) ResetLangWords(ctx context.Context, languageID int32) error {
	_, err := q.db.ExecContext(ctx, resetLangWords, languageID)
	return err
}
