// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resetdb.sql

package database

import (
	"context"
)

const resetWords = `-- name: ResetWords :exec
DELETE FROM words
`

func (q *Queries) ResetWords(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetWords)
	return err
}
