// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seedlanguages.sql

package database

import (
	"context"
)

const seedLanguages = `-- name: SeedLanguages :exec
INSERT INTO languages (code, name) VALUES 
    ('it', 'Italian'),
    ('cz', 'Czech')
`

func (q *Queries) SeedLanguages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedLanguages)
	return err
}
