// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: updateword.sql

package database

import (
	"context"
)

const updateWord = `-- name: UpdateWord :exec
UPDATE words
SET last_seen_at = now(), frequency = frequency + 1
WHERE token_name = $1
`

func (q *Queries) UpdateWord(ctx context.Context, tokenName string) error {
	_, err := q.db.ExecContext(ctx, updateWord, tokenName)
	return err
}
