// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: updatewordprompted.sql

package database

import (
	"context"
)

const updateWordPrompted = `-- name: UpdateWordPrompted :exec
UPDATE words
SET promted_user_to_mark = true
WHERE token_name = $1
`

func (q *Queries) UpdateWordPrompted(ctx context.Context, tokenName string) error {
	_, err := q.db.ExecContext(ctx, updateWordPrompted, tokenName)
	return err
}
