// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: updatewordseen.sql

package database

import (
	"context"
)

const updateWordSeen = `-- name: UpdateWordSeen :exec
UPDATE words
SET last_seen_at = now(), frequency = frequency + 1
WHERE token_name = $1 AND language_id = $2
`

type UpdateWordSeenParams struct {
	TokenName  string
	LanguageID int32
}

func (q *Queries) UpdateWordSeen(ctx context.Context, arg UpdateWordSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateWordSeen, arg.TokenName, arg.LanguageID)
	return err
}
