// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: updatewordknown.sql

package database

import (
	"context"
)

const updateWordKnown = `-- name: UpdateWordKnown :exec
UPDATE words
SET known = true
WHERE token_name = $1
`

func (q *Queries) UpdateWordKnown(ctx context.Context, tokenName string) error {
	_, err := q.db.ExecContext(ctx, updateWordKnown, tokenName)
	return err
}
