// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: updatewordprompted.sql

package database

import (
	"context"
)

const updateWordPrompted = `-- name: UpdateWordPrompted :exec
UPDATE words
SET promted_user_to_mark = true
WHERE token_name = $1 AND language_id = $2
`

type UpdateWordPromptedParams struct {
	TokenName  string
	LanguageID int32
}

func (q *Queries) UpdateWordPrompted(ctx context.Context, arg UpdateWordPromptedParams) error {
	_, err := q.db.ExecContext(ctx, updateWordPrompted, arg.TokenName, arg.LanguageID)
	return err
}
