// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: updateworkunknown.sql

package database

import (
	"context"
)

const updateWordUnKnown = `-- name: UpdateWordUnKnown :exec
UPDATE words
SET known = false
WHERE token_name = $1 AND language_id = $2
`

type UpdateWordUnKnownParams struct {
	TokenName  string
	LanguageID int32
}

func (q *Queries) UpdateWordUnKnown(ctx context.Context, arg UpdateWordUnKnownParams) error {
	_, err := q.db.ExecContext(ctx, updateWordUnKnown, arg.TokenName, arg.LanguageID)
	return err
}
