package api

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"strconv"

	"github.com/DXICIDE/MagisterLinguae/internal/repl"
)

func (h *Handler) Dictionary(w http.ResponseWriter, r *http.Request) {
	word := r.PathValue("word")

	languageID := r.URL.Query().Get("language_id")
	ID, err := strconv.Atoi(languageID)
	if err != nil {
		http.Error(w, "invalid language_id", http.StatusBadRequest)
		return
	}
	language, err := h.Db.GetLanguageById(r.Context(), int32(ID))

	httpAdress := fmt.Sprintf("https://freedictionaryapi.com/api/v1/entries/%s/%s", language.Code, word)

	response, err := http.Get(httpAdress)
	if err != nil {
		log.Printf("http.Get error: %v", err)
		http.Error(w, "internal server error", http.StatusInternalServerError)
		return
	}

	responseData, err := io.ReadAll(response.Body)
	if err != nil {
		log.Printf("io.ReadAll error: %v", err)
		http.Error(w, "internal server error", http.StatusInternalServerError)
	}
	var responseObject repl.AutoGenerated
	if err := json.Unmarshal(responseData, &responseObject); err != nil {
		log.Printf("Unmarshal error: %v", err)
		http.Error(w, "internal server error", http.StatusInternalServerError)
		return
	}

	if len(responseObject.Entries) == 0 {
		log.Printf("No definitions error: %v", err)
		http.Error(w, "word not found in dictionary", http.StatusNotFound)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(responseObject)
}
