package repl

type AutoGenerated struct {
	Word    string    `json:"word"`
	Entries []Entries `json:"entries"`
	Source  Source    `json:"source"`
}
type Language struct {
	Code string `json:"code"`
	Name string `json:"name"`
}
type Pronunciations struct {
	Type string   `json:"type"`
	Text string   `json:"text"`
	Tags []string `json:"tags"`
}
type Forms struct {
	Word string   `json:"word"`
	Tags []string `json:"tags"`
}
type Quotes struct {
	Text      string `json:"text"`
	Reference string `json:"reference"`
}
type Translations struct {
	Language Language `json:"language"`
	Word     string   `json:"word"`
}
type Senses struct {
	Definition   string         `json:"definition"`
	Tags         []string       `json:"tags"`
	Examples     []string       `json:"examples"`
	Quotes       []Quotes       `json:"quotes"`
	Synonyms     []string       `json:"synonyms"`
	Antonyms     []string       `json:"antonyms"`
	Translations []Translations `json:"translations"`
}
type Entries struct {
	Language       Language         `json:"language"`
	PartOfSpeech   string           `json:"partOfSpeech"`
	Pronunciations []Pronunciations `json:"pronunciations"`
	Forms          []Forms          `json:"forms"`
	Senses         []Senses         `json:"senses"`
	Synonyms       []string         `json:"synonyms"`
	Antonyms       []string         `json:"antonyms"`
}
type License struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}
type Source struct {
	URL     string  `json:"url"`
	License License `json:"license"`
}
