package repl

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

// stdin scan
func (state *AppState) Dictionary(word string) error {

	httpAdress := fmt.Sprintf("https://freedictionaryapi.com/api/v1/entries/%s/%s", state.CurrentLanguage.Code, word)

	response, err := http.Get(httpAdress)

	if err != nil {
		return err
	}

	responseData, err := io.ReadAll(response.Body)
	if err != nil {
		return err
	}
	var responseObject AutoGenerated
	if err := json.Unmarshal(responseData, &responseObject); err != nil {
		return err
	}

	if len(responseObject.Entries) == 0 {
		fmt.Println("No definitions found for this word")
		return nil
	}

	fmt.Printf("Word: %s\n", responseObject.Word)
	for _, entry := range responseObject.Entries {
		fmt.Printf("PartOfSpeech: %s\n", entry.PartOfSpeech)
		for _, sense := range entry.Senses {
			fmt.Printf(" Definition: %s\n", sense.Definition)
			for _, tag := range sense.Tags {
				fmt.Printf("  Tags: %s\n", tag)
			}
			for _, example := range sense.Examples {
				fmt.Printf("  Example: %s\n", example)
			}
		}
	}

	fmt.Printf("\nSource: %s\n", responseObject.Source.URL)
	fmt.Println("License by:")
	fmt.Printf("name: %s\n", responseObject.Source.License.Name)
	fmt.Printf("url: %s\n\n", responseObject.Source.License.URL)

	return nil
}
